#服务端口
server:
  port: 8002
#服务别名，注册到注册中心的服务别名
spring:
  application:
    name: yinzhh-order

eureka:
  instance:
    # 注册中心IP地址
    hostname: localhost
    # 心跳检测与续约时间
    # 心跳时间，即服务续约间隔时间.测试时将值设置小些，保证关闭服务后注册中心能及时踢除服务 默认30
    # lease-renewal-interval-in-seconds: 5
    # 发呆时间，即服务续约到期时间.Eureka服务端在收到最后一次心跳之后等待的时间上限，单位秒，超时则踢除（客户端告诉服务器按照此规则） 默认90
    # lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:8000/eureka/,http://${eureka.instance.hostname}:8100/eureka/ #,http://${eureka.instance.hostname}:8200/eureka/
    # 需要将服务注册到eureka注册中心
    register-with-eureka: true
    # 检索服务
    fetch-registry: true

















